# Network configuration variables
variable "private_network_ip_range" {
  type        = string
  description = "Private network IP range"
  default     = "10.0.0.0/16"
}

variable "private_network_zone" {
  type        = string
  description = "Private network zone"
  default     = "eu-central"
}

variable "private_network_type" {
  type        = string
  description = "Private network type"
  default     = "cloud"
}

variable "private_network_subnet_ip_range" {
  type        = string
  description = "Private network subnet IP range"
  default     = "10.0.1.0/24"
}

# Kubernetes cluster node configuration variables
variable "node_image" {
  type        = string
  description = "Kubernetes cluster node image"
  default     = "ubuntu-24.04"
}

variable "node_type" {
  type        = string
  description = "Kubernetes cluster node type"
  default     = "cax11"
}

variable "node_location" {
  type        = string
  description = "Kubernetes cluster node location"
  default     = "fsn1"
}

variable "node_enable_ipv4" {
  type        = bool
  description = "Kubernetes cluster use IPv4 networking"
  default     = true
}

variable "node_enable_ipv6" {
  type        = bool
  description = "Kubernetes cluster use IPv6 networking"
  default     = true
}

variable "master_node_ip" {
  type        = string
  description = "Kubernetes cluster master node ip"
  default     = "10.0.1.1"
}

variable "ssh_keys" {
  type        = list(string)
  description = "Optional names or IDs of SSH keys that already exist in the Hetzner project. They are installed on the nodes' root user in addition to `ssh_public_key`."
  default     = []
  nullable    = false
}

variable "worker_nodes_number" {
  type        = number
  description = "Number of worker nodes in Cluster"
  default     = 2
}

variable "master_nodes_number" {
  type        = number
  description = "Number of master nodes in Cluster"
  default     = 1
}

# SSH keys configuration
# The only key material taken from input is the operator's own public key.
# The key pairs used between the nodes are generated by the module itself.
variable "ssh_public_key" {
  type        = string
  description = "Public SSH key of your own machine. It is uploaded to the Hetzner project and installed on the root and cluster users of every node."

  validation {
    condition     = can(regex("^(ssh-rsa|ssh-ed25519|ecdsa-sha2-nistp(256|384|521)) ", trimspace(var.ssh_public_key)))
    error_message = "ssh_public_key must be an OpenSSH public key, e.g. the contents of ~/.ssh/id_ed25519.pub."
  }
}

variable "ssh_key_algorithm" {
  type        = string
  description = "Algorithm used for the SSH key pairs generated for the master and worker nodes. One of RSA, ECDSA, ED25519."
  default     = "ED25519"

  validation {
    condition     = contains(["RSA", "ECDSA", "ED25519"], var.ssh_key_algorithm)
    error_message = "ssh_key_algorithm must be one of RSA, ECDSA, ED25519."
  }
}

variable "ssh_key_rsa_bits" {
  type        = number
  description = "Key size of the generated SSH key pairs. Only used when ssh_key_algorithm is RSA."
  default     = 4096
}

variable "ssh_key_ecdsa_curve" {
  type        = string
  description = "Curve of the generated SSH key pairs. Only used when ssh_key_algorithm is ECDSA."
  default     = "P384"
}

variable "default_labels" {
  type        = map(string)
  description = "Default labels for resources"
  default = {
    "Confidentiality" = "C3"
    "Project"         = "Hetzner Kubernetes"
  }
}
