# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "hetzner-k8s-remote-state"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "k8s/terraform.tfstate"
    region         = "eu-central-1"
  }
}
