# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
    required_version = ">= 1.5.5"

    required_providers {
        hcloud = {
            source  = "hetznercloud/hcloud"
            version = ">= 1.45"
        }
    }
}
