module "hcloud_kubernetes_cluster" {
  source = "../../"

  worker_nodes_number = 2
  master_nodes_number = 1

  node_image    = "ubuntu-24.04"
  node_type     = "cax11"
  node_location = "fsn1"

  node_enable_ipv4 = true
  node_enable_ipv6 = true

  # The only key you provide: the public key of your own machine.
  # The key pairs used between master and worker nodes are generated by the module.
  # Optional - leave it unset and pass `ssh_keys` instead if the key already
  # exists in your Hetzner project.
  ssh_public_key = var.ssh_public_key

  private_network_ip_range        = "10.0.0.0/16"
  private_network_zone            = "eu-central"
  private_network_type            = "cloud"
  private_network_subnet_ip_range = "10.0.1.0/24"
  master_node_ip                  = "10.0.1.1"
}
