module "hcloud_kubernetes_cluster" {
  source = "../../"

  worker_nodes_number = 2
  master_nodes_number = 1

  node_image       = "ubuntu-24.04"
  master_node_type = "cax11"
  worker_node_type = "cax11"
  node_location    = "fsn1"

  # When ipv6 and ipv4 addresses will be disabled to have
  # connection to the kubeapi we recommend to use tailscale
  # It can be easly switched on using variable use_tailscale
  use_public_ipv4 = true
  use_public_ipv6 = true

  # Placement Group is used to decrease the potential outage in case of issue with physical server
  # It is responsible for spreading the VMs on different physical servers
  # When particular server will crash then only one VM will crash
  use_placement_group = true

  # The only key you provide: the public key of your own machine.
  # The key pairs used between master and worker nodes are generated by the module.
  # Optional - leave it unset and pass `ssh_keys` instead if the key already
  # exists in your Hetzner project.
  ssh_public_key = var.ssh_public_key

  private_network_ip_range        = "10.0.0.0/16"
  private_network_zone            = "eu-central"
  private_network_type            = "cloud"
  private_network_subnet_ip_range = "10.0.1.0/24"
}
